### ISSUE TITLE
Bug with  extract_docs_from_index.py 

### ISSUE THREAD

**Issue by nguyenvo09** [Georgetown-IR-Lab/cedr#11]
When I run command 
```
awk '{print $3}' data/robust/*.run | python extract_docs_from_index.py indri PATH_TO_INDRI_INDEX > data/robust/documents.tsv

```
I got error like:
```
Traceback (most recent call last):
  File "extract_docs_from_index.py", line 60, in <module>
    main_cli()
  File "extract_docs_from_index.py", line 48, in main_cli
    doc_extractor = INDEX_MAP[args.index_type](args.index_path)
  File "extract_docs_from_index.py", line 8, in indri_doc_extractor
    index = pyndri.Index(path)
  File "/root/anaconda3/lib/python3.6/site-packages/pyndri/__init__.py", line 52, in __init__
    super(Index, self).__init__(*args, **kwargs)
OSError: ../src/Parameters.cpp(469): Couldn't open parameter file 'indri-5.14/manifest' for reading.
it seems I need to do some indexing first. how could I do that? 
```

**Comment by seanmacavaney** [comment]
Hi @nguyenvo09,

We provide `extract_docs_from_index.py` to allow you to easily extract document content from an Anserini or Indri index. (You will need to have an index built for the initial document rankings anyway.) Please refer to Anserini documentation ([here](https://github.com/castorini/Anserini#running-standard-ir-experiments)) or Indri documentation ([here](https://lemur.sourceforge.io/indri/IndriIndexer.html)) for help building an index.

If you are using a different index format, we welcome contributions to `extract_docs_from_index.py` to support additional formats!

**Comment by nguyenvo09** [comment]
Could you provide a link to download `document.tsv` file so that I can quickly run experiments? Thank you very much.

**Comment by seanmacavaney** [comment]
Hi @nguyenvo09,

It is my understanding that I cannot distribute the datasets we used in the CEDR paper per the license agreements. You will need to go through proper channels to obtain them. For Robust04, you will need to sign agreements with NIST to get a copy. Information can be found [here](https://trec.nist.gov/data/cd45/index.html). There's a similar process for [ClueWeb09](https://lemurproject.org/clueweb09/index.php#Obtaining) and [ClueWeb12](https://lemurproject.org/clueweb12/index.php#Obtaining) (since these collections are so large, you'll need to pay for the drives and shipment of the drives).

There are also freely-available datasets that you could experiment with that were not in the paper. For instance, [MS-MARCO](http://www.msmarco.org/dataset.aspx), [TREC CAR](http://trec-car.cs.unh.edu/), and [ANTIQUE](https://ciir.cs.umass.edu/downloads/Antique/).

I hope this helps!
