### ISSUE TITLE
how to get a pre-processing index file for lucene or indri

### ISSUE THREAD

**Issue by JrJessyLuo** [Georgetown-IR-Lab/cedr#9]
In the guideline notes,be sure to use an index that has appropriate pre-processing.
But I didn't know how to build the index file.I did't the robust04 or clubweb09 document dataset either.
I want to replicate the experiment,but I can't work it out now because of this.
Can anyone help me?

**Comment by seanmacavaney** [comment]
Hi,

You will first need to get a copy of the document collections. For Robust04, you will need to sign agreements with NIST to get a copy. Information can be found [here](https://trec.nist.gov/data/cd45/index.html). There's a similar process for [ClueWeb09](https://lemurproject.org/clueweb09/index.php#Obtaining) and [ClueWeb12](https://lemurproject.org/clueweb12/index.php#Obtaining) (since these collections are so large, you'll need to pay for the drives and shipment of the drives).

Once you have the data, you can extract the document content however you like into the data files. However, since you probably will have built indices anyway, we made a way to extract the content  from the indices (`extract_docs_from_index.py`). An easy guide for building Anserini indices from both the datasets can be found [here](https://github.com/castorini/anserini/blob/master/docs/regressions-robust04.md#indexing) and [here](https://github.com/castorini/anserini/blob/master/docs/regressions-cw09b.md#indexing) (be sure to use the `-storeTransformedDocs` flag).

**Comment by JrJessyLuo** [comment]
OK,I got it.Thank you for you help.
